### ISSUE TITLE
Task completion %

### ISSUE THREAD

**Issue by adfaure** [agateau/yokadi#55]
Hi, I don't know if it is the right place to post this.

It would be nice if we can specified a percentage completion for a task.  
For example : `yokadi t_tast_mark 77% <idTask>`

Don't hesitate to lead me to a better place for this post.
Greetings

**Comment by agateau-g** [comment]
Hi, it's a great place to post feature requests!

I am not convinced being able to define completion percentage would be that useful: how would you know if a task is 77% or 79% done? Or do you have a specific use case in mind?

I think it would be more useful to be able to get a (read-only) completion percentage for a whole project instead, so if 3 out of 5 tasks of a project are done then it's 60% complete. What do you think?

**Comment by agateau-g** [comment]
Hi, it's a great place to post feature requests!

I am not convinced being able to define completion percentage would be that useful: how would you know if a task is 77% or 79% done? Or do you have a specific use case in mind?

I think it would be more useful to be able to get a (read-only) completion percentage for a whole project instead, so if 3 out of 5 tasks of a project are done then it's 60% complete. What do you think?

**Comment by adfaure** [comment]
Hi,
I agree with you, it is hard to define the exact percentage of completion of one task. But today I was working on a project report and I decided to complete it later. When I'll see my tasks list it would be great if I could see something like this : 

    ID|Title            |U  |S|Age     |Due date                  
    --------------------------------------------------------------
    2 |rapport RM       |0  |Almost done|5h 27m  |                          
    3 |reviser Génie Log|0  |N|5h 27m  |                          
    4 |reviser bdd      |0  |N|5h 27m  |


It will remind the user of the work almost done by a number estimated (entered) by him/herself on a task. It's just a number like 97% put by the user before leaving his project. Like a note or a small sentence like "almost done", or "need a conclusion" 
But maybe this feature is too specific.

By the way your idea is great, but in my mind it's thought about something else.

**Comment by agateau** [comment]
I think this is indeed a bit too specific. I like the idea of the 3 different status because it makes it possible to have a Kanban-like workflow where tasks goes from todo => in-progress => done. Having a single state for in-progress makes it easy to check you do not have too many in-progress tasks at the same time.

I agree my idea is something else, need to find time to work on it one day...

I am going to close this issue, hope you don't mind.
