### ISSUE TITLE
t_medit error 

### ISSUE THREAD

**Issue by drneill** [agateau/yokadi#57]
This error message gets thrown by Vim, when I write/quit.
---------------8<----------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/yokadi/ycli/main.py", line 110, in onecmd
    return Cmd.onecmd(self, line)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/cmd.py", line 217, in onecmd
    return func(arg)
  File "/usr/local/lib/python3.5/site-packages/yokadi/ycli/taskcmd.py", line 711, in do_t_medit
    newText = tui.editText(newText, suffix=".medit")  File "/usr/local/lib/python3.5/site-packages/yokadi/ycli/tui.py", line 98, in editText
    raise Exception()
Exception
--
Python: 3.5.1 (default, Jan 22 2016, 08:54:32)  [GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)]SQL Alchemy: 1.0.12
OS: Darwin (15.6.0)
Yokadi: 1.1.0

**Comment by agateau** [comment]
This is very odd. Yokadi finds the editor to run through the EDITOR environment variable. Do you have it set to something special? I just pushed a commit to the `dev` branch which should print a bit more information about what's going wrong. Can you give it a try?

**Comment by drneill** [comment]
I sure will, but will have to wait for the weekend, when I’ll next have
access to my home computer. The issue could relate to the fact that I have
to ssh in when I use the t_medit function.

Yokadi had been giving me an ascii error, which I worked around by changing
an environmental variable:

export LANG=en_US.UTF-8


On October 4, 2016 at 6:22:05 AM, Aurélien Gâteau (notifications@github.com)
wrote:

This is very odd. Yokadi finds the editor to run through the EDITOR
environment variable. Do you have it set to something special? I just
pushed a commit to the dev branch which should print a bit more information
about what's going wrong. Can you give it a try?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/agateau/yokadi/issues/57#issuecomment-251350977>, or mute
the thread

**Comment by drneill** [comment]
The error is fixed- a mistake on my part. When logging in, adding export LANG=en_US.UTF-8, then sourcing .bashrc brought Yokadi back from VIM. I now have source .bashrc set up as an environmental variable, so that I don't have to manually type it in whenever using the t_medit function.

**Comment by agateau** [comment]
Nice, thanks for coming back. Closing this issue then.
