### ISSUE TITLE
Logging feature

### ISSUE THREAD

**Issue by Jefficus** [agateau/yokadi#59]
As it stands, I can use the t_describe feature to keep a running log of notes related to a task, but there's no way to easily parse out what parts of the note were entered on what day, so I have to remember to add date stamps in the file whenever I add something. That sort of works, but what would be way more effective would be to add l_add, l_edit, l_list commands to permit the addition of individual dated log entries on particular tasks, and then maybe a t_show_log command to summarize them in a tidy display.

**Comment by agateau** [comment]
Hi, that is not really the goal of the description feature of Yokadi. It has been created to be able to enter long block of texts. I use it to detail what I have to do for a complex task, often before breaking it down into shorter tasks, to store reproduction steps for a bug or to draft blog posts. Others use it to record minutes of a meeting.

I am worried adding dated log entries would complicate the database model too much, sorry.

**Comment by Jefficus** [comment]
I think you misunderstood my proposal. I was suggesting a new table and data type called Log, with associated commands l_add, l_list, etc. That way the t.description field can remain devoted to block text about the task details, while the log table would be the place for incremental progress notes about the task.

**Comment by agateau** [comment]
I think that's what I understood, and indeed, it's "just another table", but then you have to start thinking about how to list logs: do they appear in `t_list` or is there just an indicator that the task has attached logs? How to search them, does `t_list` actually search for text in logs as well?
