### ISSUE TITLE
Is it possible to import/export the data?

### ISSUE THREAD

**Issue by hoijui** [agateau/yokadi#61]
Hello! :-)
From a quick browse of the documentation, I could not find any reference of import or exporting of tasks/data.
Is it possible?

To me, this is a very important feature, as I already have some tasks, and in case I adopt yokadi, but later would like to or have to move to an other tool, I would like to have the possibility to do so relatively easily (without figuring out SQL commands).

Of course the question is: to/from which format?\
For me personally, some simple plain-text format or CSV would do. Anything that can easily be parsed with something like AWK and then converted to some other tools format with a little script.
Optimally, it would be a widely used standard if that exists, or the format of a commonly used tool like [todo.txt](https://github.com/todotxt/todo.txt).

have a good day!

**Comment by agateau** [comment]
Hi, sorry for the late answer!

There is no way to import from other formats, but you can export data through the different output formats of `t_list`. Both xml and csv are supported, but xml is probably the most appropriate to export the whole database.
